name: David Kazaryan
favicon: null
layout_spectrum: 0.5230210204608738
typography_spectrum: 0.07017142092809081
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.12712048995308578
  lightness: 0.7353103342466056
  saturation: 0.5982928182929754
  rhythmicContrast: 0.22422901610843837
purpose: []
